apiVersion: apps/v1
kind: Deployment
metadata:
  name: smile_app
spec:
  replicas: 3  # Set the number of replicas based on your requirements
  selector:
    matchLabels:
      app: smile_app
  template:
    metadata:
      labels:
        app: smile_app
    spec:
      containers:
      - name: smile_app
        #image: your-docker-hub-username/smile_app:latest  # Replace with your Docker image
        image: smile_app:latest
        ports:
        - containerPort: 5000